In [1]:
import pandas as pd

In [2]:
df_futbol = pd.read_csv('players_20_new.csv')
df_futbol.set_index('short_name', inplace=True)
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### 1. Fijar valor a una celda

In [4]:
# Actualizar altura de L. Messi
df_futbol.loc['L. Messi', 'height_cm'] = 175

In [5]:
# Mostrar DF
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### 3 Fijar valor de toda la columna

In [10]:
# Fijar tamano de 190 a todos los jugadores
df_futbol.loc[:,'height_cm'] = round(df_futbol.loc[:,'height_cm'].mean())

In [11]:
# Mostrar DF
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,181,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,181,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,181,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,181,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,181,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,181,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,181,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,181,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,181,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,181,78,China PR,Hebei China Fortune FC

### 3 Fijar valor a toda la fila

In [12]:
# Obtener todas las columnas que corresponden al jugador rankeado utimo al jurgo fifa
df_futbol.iloc[-1,:]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         181
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [14]:
# Fijar valor nulo a todas las columnas que corresponden al jugador rankeado
import numpy as np

df_futbol.iloc[-1,:] = np.nan

In [15]:
# Mostrar DF
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,181.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,181.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,181.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,181.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,181.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,181.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,181.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,181.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,181.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 4 Fijas valor a multiples celdas

In [16]:
# Fijar valor a todos los items que hacen match con la lita de nombres


df_futbol.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm']] = 175

In [17]:
# Mostrar DF
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,181.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,181.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,181.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,181.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,181.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,181.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,181.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 5 Fijar valor para filas que cumplen una condicion

In [18]:
# Fijar valor para filas que cumplen una condicion
columns = ['age', 'dob', 'height_cm', 'weight_kg']

df_futbol.loc[df_futbol['height_cm'] > 180, columns] = 0

In [19]:
# Mostrar DF
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN