In [1]:
import pandas as pd

In [3]:
df_futbol = pd.read_csv('players_20_new.csv')
df_futbol.set_index('short_name', inplace=True)
df_futbol

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

### 1 sample()

In [17]:
# Extraer 10 elementos aleatorios de la columna "nationality"
df_futbol['nationality'].sample(n=10, random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [21]:
# Extraer el 20% de muestra aleatoria del DF
df_futbol.sample(frac=0.2, random_state=999)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
A. Feick,Arne Feick,31,1988-04-01,179,79,Germany,1. FC Heidenheim 1846
B. Manosalva,Brayan Manosalva,21,1997-07-14,185,78,Chile,CD Huachipato
Edigar Junio,Edigar Junio Teixeira Lima,28,1991-05-06,174,72,Brazil,Yokohama F. Marinos
G. Muzinga,Glody Ngonda Muzinga,24,1994-12-31,175,70,DR Congo,Dijon FCO
F. Al Birekan,Firas Al Birekan,19,2000-05-14,181,75,Saudi Arabia,Al Nassr
...,...,...,...,...,...,...,...
M. Kobylański,Martin Kobylański,25,1994-03-08,178,75,Poland,Eintracht Braunschweig
N. Contini,Nikita Contini,23,1996-05-21,190,82,Ukraine,Virtus Entella
L. Kalinić,Lovre Kalinić,29,1990-04-03,201,99,Croatia,Aston Villa
S. Ntshangase,Siphelele Ntshangase,26,1993-05-11,172,65,South Africa,Kaizer Chiefs
I. Vujica,Ivan Vujica,22,1997-04-20,180,83,Australia,Western United FC

In [24]:
# Imcrementar la muestra -> frac>1 (obs: el parametro replace tiene que er Ture cuando el parametro frac>1)
df_futbol.sample(frac=2, replace=True, random_state=66)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Víctor,Víctor García Raja,22,1997-01-01,180,77,Spain,Real Valladolid CF
J. Clarke-Harris,Jonson Clarke-Harris,24,1994-07-21,183,78,England,Bristol Rovers
K. Gunnarshaug,Kristoffer Gunnarshaug,20,1999-05-11,180,73,Norway,FK Haugesund
A. Rocha,Aldo Rocha,26,1992-11-06,167,68,Mexico,Monarcas Morelia
Flávio,Flávio da Silva Ramos,25,1994-05-12,191,86,Brazil,Gençlerbirliği SK
...,...,...,...,...,...,...,...
Q. Lecoeuche,Quentin Lecoeuche,25,1994-02-04,172,65,France,FC Lorient
Andreas Pereira,Andreas Hugo Hoelgebaum Pereira,23,1996-01-01,178,71,Brazil,Manchester United
B. Lennon,Brooks Lennon,21,1997-09-22,177,70,United States,Real Salt Lake
O. Diagne,Ousseynou Diagne,20,1999-06-05,190,77,Senegal,Le Mans FC
Joaquim Adão,Joaquim Adão,26,1992-07-14,176,75,Angola,FC Sion